recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LeJ6cMSAAAAAJzoM0lyBZv-Pg32jlQaA61Gc-4P"
	privateKey = "6LeJ6cMSAAAAAEknqVk_YRpp9qIhSomqtNo0WLSK"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = "6LeJ6cMSAAAAAJzoM0lyBZv-Pg32jlQaA61Gc-4P"
    privateKey = "6LeJ6cMSAAAAAEknqVk_YRpp9qIhSomqtNo0WLSK"
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}